name: Deploy to AlwaysData via SSH (Password)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.19

      - name: Install dependencies
        run: npm install

      - name: Clean previous builds
        run: rm -rf ./dist

      - name: Build Angular app (static only)
        run: npx ng build --configuration production --base-href ./ --deploy-url ./

      - name: List dist directory (debug)
        run: ls -R ./dist/portfolio-cloe/browser

      - name: Deploy only browser files to AlwaysData
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./dist/portfolio-cloe/browser/*"
          target: "${{ secrets.SSH_TARGET_DIR }}"
          debug: true
