name: Deploy to AlwaysData via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.19

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod --configuration production

      - name: Deploy via SSH (Password)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./dist/portfolio-cloe/*"
          target: "${{ secrets.SSH_TARGET_DIR }}"
